// <auto-generated />
namespace EmpleoJIC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Field_Address_Telephone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Field_Address_Telephone));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151830520_Field_Address_Telephone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
